@baseUrl = http://localhost:3000
@baseUrl = https://gaslow-api.mattianatali.com
# @baseUrl = https://gaslow.herokuapp.com

###
# Update stations
POST {{baseUrl}}/stations/update

###
# Find by position
GET {{baseUrl}}/stations/find/location?lat=45.695&lng=9.67

###
# Find by ids
GET {{baseUrl}}/stations/find?ids=11482,6373
